export const DEFAULT_LOCALE = "en-US";
export const DEFAULT_DATE_FORMAT = "MMM DD";
export const DEFAULT_TIME_FORMAT = "hh:mm A";

export const SORT_BY_EVENTS_OPTIONS: Option[] = [
  { label: "Title", value: "title" },
  { label: "Event date", value: "event date" },
  { label: "Organizer", value: "organizer" },
];

export const EVENTS_LEAD_CHANEL_OPTIONS: Option[] = [
  { label: "Social media", value: "social-media" },
  { label: "Friends", value: "friends" },
  { label: "Found myself", value: "found-myself" },
];

export const ANIMALS_LIST = [
  "alligator",
  "anteater",
  "armadillo",
  "auroch",
  "axolotl",
  "badger",
  "bat",
  "beaver",
  "buffalo",
  "camel",
  "capybara",
  "chameleon",
  "cheetah",
  "chinchilla",
  "chipmunk",
  "chupacabra",
  "cormorant",
  "coyote",
  "crow",
  "dingo",
  "dinosaur",
  "dolphin",
  "duck",
  "elephant",
  "ferret",
  "fox",
  "frog",
  "giraffe",
  "gopher",
  "grizzly",
  "hedgehog",
  "hippo",
  "hyena",
  "ibex",
  "ifrit",
  "iguana",
  "jackal",
  "kangaroo",
  "koala",
  "kraken",
  "lemur",
  "leopard",
  "liger",
  "llama",
  "manatee",
  "mink",
  "monkey",
  "moose",
  "narwhal",
  "orangutan",
  "otter",
  "panda",
  "penguin",
  "platypus",
  "pumpkin",
  "python",
  "quagga",
  "rabbit",
  "raccoon",
  "rhino",
  "sheep",
  "shrew",
  "skunk",
  "squirrel",
  "tiger",
  "turtle",
  "walrus",
  "wolf",
  "wolverine",
  "wombat",
];
